apiVersion: v1
kind: Service
metadata:
  name: log-stream-service
  namespace: oncloud-ai-platform
  labels:
    app.kubernetes.io/name: log-stream-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: log-stream-service
  ports:
    - name: http
      port: 8246
      targetPort: http
      protocol: TCP
